import { generateKeyPairSync } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * Generate an Ed25519 keypair as PEM, in exactly the form `keys.ts` consumes:
 * a PKCS8 private key (importPKCS8) and an SPKI public key (importSPKI), EdDSA.
 */
export function generateKeypairPem(): { privatePem: string; publicPem: string } {
  const { privateKey, publicKey } = generateKeyPairSync('ed25519', {
    privateKeyEncoding: { format: 'pem', type: 'pkcs8' },
    publicKeyEncoding: { format: 'pem', type: 'spki' },
  });
  return { privatePem: privateKey, publicPem: publicKey };
}

const PRIVATE_VAR = 'JWT_ED25519_PRIVATE_KEY';
const PUBLIC_VAR = 'JWT_ED25519_PUBLIC_KEY';
const HEADER = '# JWT signing keys (Ed25519) — generated by `bun run gen:keys`';

/** A non-empty, uncommented `NAME=...` assignment exists (multi-line or not). */
function isVarSet(content: string, name: string): boolean {
  return new RegExp(`^${name}=.+`, 'm').test(content);
}

function envValue(pem: string): string {
  return pem.trimEnd().replaceAll('\r\n', '\n').replaceAll('\r', '\n').replaceAll('\n', '\\n');
}

function normalizeLegacyVar(content: string, name: string, keyType: 'PRIVATE' | 'PUBLIC'): string {
  const legacy = new RegExp(`^${name}="([\\s\\S]*?-----END ${keyType} KEY-----)"\\r?$`, 'm');
  return content.replace(legacy, (_match, pem: string) => `${name}=${envValue(pem)}`);
}

/** Remove an existing assignment (legacy multi-line double-quoted, or single-line). */
function stripVar(content: string, name: string): string {
  const multiline = new RegExp(`^${name}="[\\s\\S]*?"\\r?\\n?`, 'm');
  if (multiline.test(content)) {
    return content.replace(multiline, '');
  }
  return content.replace(new RegExp(`^${name}=.*\\r?\\n?`, 'm'), '');
}

function block(keys: { privatePem: string; publicPem: string }): string {
  return [
    HEADER,
    `${PRIVATE_VAR}=${envValue(keys.privatePem)}`,
    `${PUBLIC_VAR}=${envValue(keys.publicPem)}`,
    '',
  ].join('\n');
}

/**
 * Return `.env` content with the keypair added. Pure — does no IO.
 * - If both vars already use the current format and `force` is false, returns `null`.
 * - Legacy multiline values are normalized without rotating the keypair.
 * - With `force`, strips any existing block first so there are no duplicates.
 */
export function upsertEnv(
  content: string,
  keys: { privatePem: string; publicPem: string },
  { force }: { force: boolean },
): string | null {
  const normalized = normalizeLegacyVar(
    normalizeLegacyVar(content, PRIVATE_VAR, 'PRIVATE'),
    PUBLIC_VAR,
    'PUBLIC',
  );
  const hasPrivate = isVarSet(normalized, PRIVATE_VAR);
  const hasPublic = isVarSet(normalized, PUBLIC_VAR);
  if (hasPrivate && hasPublic && !force) {
    return normalized === content ? null : normalized;
  }

  let base = normalized;
  if (force || hasPrivate || hasPublic) {
    base = stripVar(stripVar(base, PRIVATE_VAR), PUBLIC_VAR).replace(
      new RegExp(`^${HEADER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\r?\\n?`, 'm'),
      '',
    );
  }

  const sep = base === '' || base.endsWith('\n') ? '\n' : '\n\n';
  return `${base}${sep}${block(keys)}`;
}

export function envFileFromArgs(args: string[]): string {
  const envFileArg = args.find((arg) => arg.startsWith('--env-file='));
  return envFileArg?.slice('--env-file='.length) || '.env';
}

async function main(): Promise<void> {
  const force = process.argv.includes('--force');
  const envFile = envFileFromArgs(process.argv);
  // gen-keys.ts lives at packages/auth/src/ — the repo root is three levels up.
  const repoRoot = resolve(import.meta.dirname, '..', '..', '..');
  const envPath = resolve(repoRoot, envFile);
  const keys = generateKeypairPem();

  if (existsSync(envPath)) {
    const updated = upsertEnv(readFileSync(envPath, 'utf8'), keys, { force });
    if (updated === null) {
      console.log(`JWT signing keys already set in ${envFile} — pass --force to regenerate.`);
      return;
    }
    writeFileSync(envPath, updated);
    console.log(`✓ Wrote ${PRIVATE_VAR} / ${PUBLIC_VAR} to ${envFile}`);
    return;
  }

  console.error(`No ${envFile} found — add these lines to your environment:\n`);
  console.log(block(keys).trimEnd());
}

if (import.meta.main) {
  await main();
}
