import { generateKeyPairSync } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * Generate an Ed25519 keypair as PEM, in exactly the form `keys.ts` consumes:
 * a PKCS8 private key (importPKCS8) and an SPKI public key (importSPKI), EdDSA.
 */
export function generateKeypairPem(): { privatePem: string; publicPem: string } {
  const { privateKey, publicKey } = generateKeyPairSync('ed25519', {
    privateKeyEncoding: { format: 'pem', type: 'pkcs8' },
    publicKeyEncoding: { format: 'pem', type: 'spki' },
  });
  return { privatePem: privateKey, publicPem: publicKey };
}

const PRIVATE_VAR = 'JWT_ED25519_PRIVATE_KEY';
const PUBLIC_VAR = 'JWT_ED25519_PUBLIC_KEY';
const HEADER = '# JWT signing keys (Ed25519) — generated by `bun run gen:keys`';

/** A non-empty, uncommented `NAME=...` assignment exists (multi-line or not). */
function isVarSet(content: string, name: string): boolean {
  return new RegExp(`^${name}=.+`, 'm').test(content);
}

/** Remove an existing assignment (multi-line double-quoted, or single-line). */
function stripVar(content: string, name: string): string {
  const multiline = new RegExp(`^${name}="[\\s\\S]*?"\\n?`, 'm');
  if (multiline.test(content)) {
    return content.replace(multiline, '');
  }
  return content.replace(new RegExp(`^${name}=.*\\n?`, 'm'), '');
}

function block(keys: { privatePem: string; publicPem: string }): string {
  return [
    HEADER,
    `${PRIVATE_VAR}="${keys.privatePem.trimEnd()}"`,
    `${PUBLIC_VAR}="${keys.publicPem.trimEnd()}"`,
    '',
  ].join('\n');
}

/**
 * Return `.env` content with the keypair added. Pure — does no IO.
 * - If both vars are already set and `force` is false, returns `null` (no-op).
 * - With `force`, strips any existing block first so there are no duplicates.
 */
export function upsertEnv(
  content: string,
  keys: { privatePem: string; publicPem: string },
  { force }: { force: boolean },
): string | null {
  const alreadySet = isVarSet(content, PRIVATE_VAR) && isVarSet(content, PUBLIC_VAR);
  if (alreadySet && !force) {
    return null;
  }

  let base = content;
  if (force) {
    base = stripVar(stripVar(base, PRIVATE_VAR), PUBLIC_VAR).replace(
      new RegExp(`^${HEADER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\n?`, 'm'),
      '',
    );
  }

  const sep = base === '' || base.endsWith('\n') ? '\n' : '\n\n';
  return `${base}${sep}${block(keys)}`;
}

async function main(): Promise<void> {
  const force = process.argv.includes('--force');
  // gen-keys.ts lives at packages/auth/src/ — the repo root is three levels up.
  const envPath = resolve(import.meta.dirname, '..', '..', '..', '.env');
  const keys = generateKeypairPem();

  if (existsSync(envPath)) {
    const updated = upsertEnv(readFileSync(envPath, 'utf8'), keys, { force });
    if (updated === null) {
      console.log(`JWT signing keys already set in .env — pass --force to regenerate.`);
      return;
    }
    writeFileSync(envPath, updated);
    console.log(`✓ Wrote ${PRIVATE_VAR} / ${PUBLIC_VAR} to .env`);
    return;
  }

  console.error('No .env found — add these lines to your environment:\n');
  console.log(block(keys).trimEnd());
}

if (import.meta.main) {
  await main();
}
