services:
  web:
    image: ${APP_IMAGE_WEB:-ghcr.io/yorch/ai-agents-observability/web:main}
    pull_policy: always
    restart: unless-stopped
    init: true
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "${WEB_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
      NODE_ENV: production

  ingest:
    image: ${APP_IMAGE_INGEST:-ghcr.io/yorch/ai-agents-observability/ingest:main}
    pull_policy: always
    restart: unless-stopped
    init: true
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - ${INGEST_PORT:-4000}:4000
    env_file:
      - .env
    environment:
      PORT: "4000"
      NODE_ENV: production

  github-app:
    image: ${APP_IMAGE_GITHUB:-ghcr.io/yorch/ai-agents-observability/github-app:main}
    pull_policy: always
    restart: unless-stopped
    init: true
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - ${GITHUB_APP_PORT:-4001}:4001
    env_file:
      - .env
    environment:
      PORT: "4001"
      NODE_ENV: production

  migrations:
    image: ${APP_IMAGE_MIGRATIONS:-ghcr.io/yorch/ai-agents-observability/migrations-runner:main}
    pull_policy: always
    build: !reset null
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    env_file:
      - .env
